"use client"
import Navigation from "@/components/Navigation";
import "./globals.css";
// import { useEffect } from "react";
import 'bootstrap/dist/css/bootstrap.css';
import { useEffect } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  useEffect(() => {
    typeof document !== undefined ? import('bootstrap/dist/js/bootstrap') : null
  }, [])

  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
